# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sipecam-visualizaciones',
                'doc_host': 'https://rausial.github.io',
                'git_url': 'https://github.com/rausial/sipecam-visualizaciones',
                'lib_path': 'sipecam_visualizaciones'},
  'syms': {'sipecam_visualizaciones.core': {'sipecam_visualizaciones.core.foo': ('core.html#foo', 'sipecam_visualizaciones/core.py')}}}